### PR TITLE
add rubocop

### LINKED ISSUE #15: Rubocop
We need basic rubocop integrations.

### PR DESCRIPTION
**Pull request by apoorv1316**
Closes #15 

Added rubocop

### CODE REVIEW

**Comment by apoorv1316** [comment]
@keshavbiswa 3-4 files need some manual changes because of robocop. I haven't changed it. Please do it.

**Comment by keshavbiswa** [comment]
You can do it on this branch itself.

**Comment by giovannism20** [comment]
Can I open another pull request to solve it @keshavbiswa ?

**Comment by giovannism20** [comment]
Maybe we can close it also @keshavbiswa. Modifications on PR #33

**Comment by keshavbiswa** [comment]
Closing this as it's completed with #33

**Pull request closed without merging**
